Fix use of getchildren with Element object
getchildren() was deprecated from Python version 3.2 so using it with
later Python versions throws an AttributeError and the activity fails
to start because of this, noticed while testing on Fedora 34 Beta with
Python version 3.9, activity failed to start with error;

1617191045.608474 ERROR root: Read: Error parsing file 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
1617191045.608657 ERROR root:  Reading setup file /usr/share/sugar/activities/Memorize.activity/demos/addition.zip

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Memorize.activity/activity.py", line 465, in change_game
    self.game.change_game(widget, game_name, size, mode, title, color)
  File "/usr/share/sugar/activities/Memorize.activity/game.py", line 330, in change_game
    size = int(self.model.data['size'])
KeyError: 'size'

Signed-off-by: Ibiam Chihurumnaya <ibiamchihurumnaya@gmail.com>