Fix fail to start when LANG es_PY.utf8
Regressions introduced by db80b371a3fd95435459671533a8b786f37b32f2.

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Memorize.activity/createcardpanel.py", line 215, in emit_update_pair
    self.cardeditor1.get_speak(),
  File "/usr/share/sugar/activities/Memorize.activity/createcardpanel.py", line 407, in get_speak
    return self.usespeak.palette.face.status.voice.language
AttributeError: Status instance has no attribute 'voice'

Fixes speak status incorrectly displayed when a card is loaded for
editing.