Remedy empty game board on XO-1 Fedora 18
Memorize-50 starts with a "Loading game" message and the game pieces are
not drawn.  Activity log shows:

Traceback (most recent call last):
  File "/home/olpc/Activities/Memorize.activity/cardtable.py", line 138, in load_game
    show_robot = self.data['origin'] != 'art4apps'
KeyError: 'origin'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sugar3/graphics/palette.py", line 191, in __map_cb
    self._widget.present()
AttributeError: '_PaletteMenuWidget' object has no attribute 'present'

The exception in load_game causes the next exception.

Fix by handling exception only.

Also fix typos.